ToonYou:
  base: ""
  path: "models/DreamBooth_LoRA/Wrenchmix.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [811756769]
  steps:          32
  guidance_scale: 5

  prompt:
    - "1girl,solo(pointy ears:1.2),white hair,silver tiara with blue jewels,blue eyes,mature female,large breasts,very long hair,earrings,(necklace:1.1),white dress,(highly detailed face and eyes:1.3)"

  n_prompt:
    - "(worst quality:2,low quality:2),(interlocked fingers,badly drawn hands and fingers,anatomically incorrect hands),negative_hand-neg,choker"