ToonYou:
  base: ""
  path: "models/DreamBooth_LoRA/MeinaPastel.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [-1]
  steps:          32
  guidance_scale: 7

  prompt:
    - "(highly detailed:1.3),(semi-rimless eyewear:1.2),(light smile:1.1),red eyes,(large breasts:1.2),(highres:1.1),(masterpiece:1.3),cinematic lighting,(highly detailed face and eyes:1.3)"

  n_prompt:
    - "(worst quality:2,low quality:2), (interlocked fingers,badly drawn hands and fingers, anatomically incorrect hands),"
